#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
from optparse import OptionParser
import hasher

aHashTable = hasher.availableHash

def copyPath(api, options, args):
    """Recursive copy or update path1 to path2"""
    if len(args) < 2:
        raise Exception('Need more arguments.')
    src = os.path.abspath(args[0])
    dst = os.path.abspath(args[1])
    api.copyPath(src, dst)

def updateFile(api, options, args):
    """Copy or update file from path1 to path2"""
    if len(args) < 2:
        raise Exception('Need more arguments.')
    src = os.path.abspath(args[0])
    dst = os.path.abspath(args[1])
    api.copyFile(src, dst)

def getHash(api, options, args):
    """Get hash of one file"""
    fname = options.filename
    if not fname:
        raise Exception('Please enter file.')
    print(api.getHash(fname))

def comparePath(api, options, args):
    fname = options.filename
    if not fname:
        raise Exception('Please enter file.')
    if not os.path.isfile(fname):
        raise Exception('Bad file: %s' %fname)
    if len(args) < 1:
        raise Exception('Please enter PATH.')
    path = os.path.abspath(args[0])
    hashStorage = hasher.DCT()
    hashStorage = hashStorage.fromJSONFile(fname)
    print('If you see no output in command line, it mean that all is well:).\n')
    api.comparePathwHashes(path, hashStorage)

def calcHash(api, options, args):
    fname = options.filename
    if not fname:
        raise Exception('Please enter file.')
    if len(args) < 1:
        raise Exception('Please enter PATH.')
    path = os.path.abspath(args[0])
    hashStorage = hasher.DCT()
    hashStorage= api.calcAllHashes(path)
    hashStorage.toJSONFile(fname)

def main():
    usage = "usage: %prog options path1 [path2]"
    parser = OptionParser(usage=usage)
    parser.add_option("-f", "--file", dest="filename",
                  help="Write to /read from FILE with hash data", metavar="FILE")
    parser.add_option("-c", "--copypath",
                  action="store_true", dest="copypath", default=False,
                  help="Copy all from path1 to path2 with updates")
    parser.add_option("-C", "--compare",
                  action="store_true", dest="comparepath", default=False,
                  help="Compare PATH with data from hash FILE")
    parser.add_option("-a", "--calchash",
                  action="store_true", dest="calchash", default=False,
                  help="Calc hashes for all files in PATH")
    parser.add_option("-u", "--updatefile",
                  action="store_true", dest="updatefile", default=False,
                  help="Copy or update file2(at path2) with file1(at path1)")
    parser.add_option("-g", "--gethash",
                  action="store_true", dest="gethash", default=False,
                  help="Get hash for one FILE (use with -f)")
    m = ",".join(aHashTable.keys() )
    parser.add_option("-m", "--hash", dest="hashmode",
                  help="Choose hash mode: %s"%m, metavar="HASH")

    (options, args) = parser.parse_args()
    hash_type = None
    if options.hashmode:
        hash_type = aHashTable.get(options.hashmode, None)
    sAPI = hasher.System(hash_type)
    try:
        if options.copypath:
            copyPath(sAPI, options, args)
            sys.exit()

        if options.updatefile:
            updateFile(sAPI, options, args)
            sys.exit()

        if options.gethash:
            getHash(sAPI, options, args)
            sys.exit()

        if options.comparepath:
            comparePath(sAPI, options, args)
            sys.exit()

        if options.calchash:
            calcHash(sAPI, options, args)
            sys.exit()

    except Exception as e:
        sys.stderr.write('Exception: %s\n' %e)
        sys.stderr.write('Use option -h for help.\n')
        sys.exit(-1)

if __name__ == '__main__':
    main()